#!/bin/bash

set -euxo pipefail

# build platform-specific Docker images
docker build -f Dockerfile.amd64   -t "${DOCKER_REPO}:latest-amd64"   .
docker build -f Dockerfile.arm32v7 -t "${DOCKER_REPO}:latest-arm32v7" .
docker build -f Dockerfile.arm64v8 -t "${DOCKER_REPO}:latest-arm64v8" .

